global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
  external_labels:
    env: prod
    monitor: monitor
    region: prometheus
scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090
  - job_name: 'node'
    static_configs:
      - targets: ['prometheus:9100']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter_dev:9187']
      - targets: ['postgres_exporter_test:9187']
